version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 9080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins_data:/var/jenkins_home
volumes:
  jenkins_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/davidblancoparis/data/jenkins_home
